title: 钟健材
description: 钟健材 - Java 研发工程师，4.5 年后端开发经验，精通 Spring Boot、微服务架构、高并发与大数据量处理。
profile_img: /assets/img/zjc-512.webp
icon_img: /assets/img/favicon.ico

name: "钟健材"
job: "JAVA 研发工程师"

#phone_number: 155 0753 0622
# address: 广东·广州
#email: jiancai.zhong.1997@gmail.com
#github_url: https://github.com/springvortex

baseurl: /resume

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
